#ifndef PS2_KEYBOARD_H_
#define PS2_KEYBOARD_H_

#include <stdint.h>

interface ps2_callback;

enum ps2_keyboard_event {
  PS2_KEY_DOWN,
  PS2_KEY_UP,
  PS2_EXTENDED_KEY_DOWN,
  PS2_EXTENDED_KEY_UP
};

enum ps2_keyboard_scancode {
  PS2_KEYBOARD_SCANCODE_A = 0x1c,
  PS2_KEYBOARD_SCANCODE_B = 0x32,
  PS2_KEYBOARD_SCANCODE_C = 0x21,
  PS2_KEYBOARD_SCANCODE_D = 0x23,
  PS2_KEYBOARD_SCANCODE_E = 0x24,
  PS2_KEYBOARD_SCANCODE_F = 0x2b,
  PS2_KEYBOARD_SCANCODE_G = 0x34,
  PS2_KEYBOARD_SCANCODE_H = 0x33,
  PS2_KEYBOARD_SCANCODE_I = 0x43,
  PS2_KEYBOARD_SCANCODE_J = 0x3b,
  PS2_KEYBOARD_SCANCODE_K = 0x42,
  PS2_KEYBOARD_SCANCODE_L = 0x4b,
  PS2_KEYBOARD_SCANCODE_M = 0x3a,
  PS2_KEYBOARD_SCANCODE_N = 0x31,
  PS2_KEYBOARD_SCANCODE_O = 0x44,
  PS2_KEYBOARD_SCANCODE_P = 0x4d,
  PS2_KEYBOARD_SCANCODE_Q = 0x15,
  PS2_KEYBOARD_SCANCODE_R = 0x2d,
  PS2_KEYBOARD_SCANCODE_S = 0x1b,
  PS2_KEYBOARD_SCANCODE_T = 0x2c,
  PS2_KEYBOARD_SCANCODE_U = 0x3c,
  PS2_KEYBOARD_SCANCODE_V = 0x2a,
  PS2_KEYBOARD_SCANCODE_W = 0x1d,
  PS2_KEYBOARD_SCANCODE_X = 0x22,
  PS2_KEYBOARD_SCANCODE_Y = 0x35,
  PS2_KEYBOARD_SCANCODE_Z = 0x1a,
  PS2_KEYBOARD_SCANCODE_0 = 0x45,
  PS2_KEYBOARD_SCANCODE_1 = 0x16,
  PS2_KEYBOARD_SCANCODE_2 = 0x1e,
  PS2_KEYBOARD_SCANCODE_3 = 0x26,
  PS2_KEYBOARD_SCANCODE_4 = 0x25,
  PS2_KEYBOARD_SCANCODE_5 = 0x2e,
  PS2_KEYBOARD_SCANCODE_6 = 0x36,
  PS2_KEYBOARD_SCANCODE_7 = 0x3d,
  PS2_KEYBOARD_SCANCODE_8 = 0x3e,
  PS2_KEYBOARD_SCANCODE_9 = 0x46,
  PS2_KEYBOARD_SCANCODE_GRAVE = 0x0e,
  PS2_KEYBOARD_SCANCODE_MINUS = 0x4e,
  PS2_KEYBOARD_SCANCODE_EQUALS = 0x55,
  PS2_KEYBOARD_SCANCODE_BACKSLASH = 0x5d,
  PS2_KEYBOARD_SCANCODE_SPACE = 0x66,
  PS2_KEYBOARD_SCANCODE_TAB = 0x0d,
  PS2_KEYBOARD_SCANCODE_CAPSLOCK = 0x58,
  PS2_KEYBOARD_SCANCODE_LSHIFT = 0x12,
  PS2_KEYBOARD_SCANCODE_LCTRL = 0x14,
  PS2_KEYBOARD_SCANCODE_LALT = 0x11,
  PS2_KEYBOARD_SCANCODE_RSHIFT = 0x59,
  PS2_KEYBOARD_SCANCODE_RETURN = 0x5a,
  PS2_KEYBOARD_SCANCODE_ESCAPE = 0x76,
  PS2_KEYBOARD_SCANCODE_F1 = 0x05,
  PS2_KEYBOARD_SCANCODE_F2 = 0x06,
  PS2_KEYBOARD_SCANCODE_F3 = 0x04,
  PS2_KEYBOARD_SCANCODE_F4 = 0x0c,
  PS2_KEYBOARD_SCANCODE_F5 = 0x03,
  PS2_KEYBOARD_SCANCODE_F6 = 0x0b,
  PS2_KEYBOARD_SCANCODE_F7 = 0x83,
  PS2_KEYBOARD_SCANCODE_F8 = 0x0a,
  PS2_KEYBOARD_SCANCODE_F9 = 0x01,
  PS2_KEYBOARD_SCANCODE_F10 = 0x09,
  PS2_KEYBOARD_SCANCODE_F11 = 0x78,
  PS2_KEYBOARD_SCANCODE_F12 = 0x07,
  PS2_KEYBOARD_SCANCODE_SCROLLLOCK = 0x7e,
  PS2_KEYBOARD_SCANCODE_LEFTBRACKET = 0x54,
  PS2_KEYBOARD_SCANCODE_NUMLOCKCLEAR = 0x77,
  PS2_KEYBOARD_SCANCODE_KP_MULTIPLY = 0x7c,
  PS2_KEYBOARD_SCANCODE_KP_MINUS = 0x7b,
  PS2_KEYBOARD_SCANCODE_KP_PLUS = 0x79,
  PS2_KEYBOARD_SCANCODE_KP_PERIOD = 0x71,
  PS2_KEYBOARD_SCANCODE_KP_0 = 0x70,
  PS2_KEYBOARD_SCANCODE_KP_1 = 0x69,
  PS2_KEYBOARD_SCANCODE_KP_2 = 0x72,
  PS2_KEYBOARD_SCANCODE_KP_3 = 0x7a,
  PS2_KEYBOARD_SCANCODE_KP_4 = 0x6b,
  PS2_KEYBOARD_SCANCODE_KP_5 = 0x73,
  PS2_KEYBOARD_SCANCODE_KP_6 = 0x74,
  PS2_KEYBOARD_SCANCODE_KP_7 = 0x6c,
  PS2_KEYBOARD_SCANCODE_KP_8 = 0x75,
  PS2_KEYBOARD_SCANCODE_KP_9 = 0x7d,
  PS2_KEYBOARD_SCANCODE_RIGHTBRACKET = 0x5b,
  PS2_KEYBOARD_SCANCODE_SEMICOLON = 0x4c,
  PS2_KEYBOARD_SCANCODE_APOSTROPHE = 0x52,
  PS2_KEYBOARD_SCANCODE_COMMA = 0x41,
  PS2_KEYBOARD_SCANCODE_PERIOD = 0x49,
  PS2_KEYBOARD_SCANCODE_SLASH = 0x4a
};

enum ps2_keyboard_extended_scancode {
  PS2_KEYBOARD_EXTENDED_SCANCODE_LGUI = 0x1f,
  PS2_KEYBOARD_EXTENDED_SCANCODE_RCTRL = 0x14,
  PS2_KEYBOARD_EXTENDED_SCANCODE_RGUI = 0x27,
  PS2_KEYBOARD_EXTENDED_SCANCODE_RALT = 0x11,
  PS2_KEYBOARD_EXTENDED_SCANCODE_APPLICATION = 0x2f,
  PS2_KEYBOARD_EXTENDED_SCANCODE_INSERT = 0x70,
  PS2_KEYBOARD_EXTENDED_SCANCODE_HOME = 0x6c,
  PS2_KEYBOARD_EXTENDED_SCANCODE_PAGEUP = 0x7d,
  PS2_KEYBOARD_EXTENDED_SCANCODE_DELETE = 0x71,
  PS2_KEYBOARD_EXTENDED_SCANCODE_END = 0x69,
  PS2_KEYBOARD_EXTENDED_SCANCODE_PAGEDOWN = 0x7a,
  PS2_KEYBOARD_EXTENDED_SCANCODE_UP = 0x75,
  PS2_KEYBOARD_EXTENDED_SCANCODE_LEFT = 0x6b,
  PS2_KEYBOARD_EXTENDED_SCANCODE_DOWN = 0x72,
  PS2_KEYBOARD_EXTENDED_SCANCODE_RIGHT = 0x74,
  PS2_KEYBOARD_EXTENDED_SCANCODE_KP_DIVIDE = 0x4a,
  PS2_KEYBOARD_EXTENDED_SCANCODE_KP_ENTER = 0x5a
};

interface ps2_keyboard_callback {
  void event(enum ps2_keyboard_event type, uint8_t data);
};

[[distributable]]
void ps2_keyboard(server interface ps2_callback,
                    client interface ps2_keyboard_callback);

void ps2_keyboard_print_event(enum ps2_keyboard_event type, uint8_t data);

#endif /* PS2_KEYBOARD_H_ */
