#ifndef DEBUG_CONF_H_
#define DEBUG_CONF_H_

#define DEBUG_PRINT_ENABLE_CHIP8_CPU 0
#define DEBUG_PRINT_ENABLE_CHIP8_SCREEN 0
#define DEBUG_PRINT_ENABLE_CHIP8_KEYS 0
#define XASSERT_ENABLE_ASSERTIONS 0

#endif /* DEBUG_CONF_H_ */
